### ISSUE TITLE
Uncaught TypeError: Cannot read property 'createRenderer' of undefined

### ISSUE THREAD

**Issue by Demonium** [jberthe/generator-app-fiori#1]
Hi,
In the launchpad.html we get an error :
Uncaught TypeError: Cannot read property 'createRenderer' of undefined line 116 
  var oContent = sap.ushell.Container.createRenderer();
Container is undefined

**Comment by jberthe** [comment]
Hi,

Can you provide me your folder structure ? Is you ui5 folder (which contains the SAPui5 library) is in the correct position ? Which version of SAPui5 do you use?

Regards,

**Comment by jberthe** [comment]
Without any information I should close this issue.
