### ISSUE TITLE
Client under 100 cause connection issue

### ISSUE THREAD

**Issue by jberthe** [jberthe/generator-app-fiori#7]
When a client for ABAP server is for instance 002, then the generator set '2' instead of '002'. Thus, during the connection, the browser show up the credential popup.

**Comment by gregorwolf** [comment]
Any hint to where this needs to be corrected?

**Comment by jberthe** [comment]
I have to add leading zero when the client is under 100. Maybe I will work on it tomorrow.

**Comment by jberthe** [comment]
Resolved int he version 1.3.1
